
# Site settings

url: "http://jamesralexander.com/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

# baseurl: /
permalink: /blog/content/:title

# google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

# Forces https everywhere in your website, except when you serve it locally

# force-https: False

#############
# HTML Head #
#############

author: "James Alexander"
lang: "en"
title: "{ Tales from the Whitespace }"
favicon: "/img/HeyJames.ico"
description: "Blog and website of James Alexander, blogging mainly for tech and ballroom dance. Opinions expressed are mine."
keywords: "james, alexander, yanigisawa, ballroom, dance, python, raspberry, pi, jekyll, theme"

################
# Intro layout #
################

# black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/Pearl-Lake-Blue-Water.jpg"
me-img: "/img/ProfilePic.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "No matter where you go, there you are."
  - text: "Software Developer by day, Ballroom dancer by night."

########
# Blog #
########

post-preview-words: 128

paginate: 5

fb-share: True
twitter-share: True
reddit-share: False
disqus-shortname: "yanigisawa"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/career/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "james@jamesralexander.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/yanigisawa"
  - title: "twitter"
    url: "https://twitter.com/yanigisawa"
  - title: "youtube"
    url: "https://youtube.com/yanigisawa"
  - title: "github"
    url: "https://github.com/yanigisawa"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/yanigisawa"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  # Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
highlighter: pygments
markdown: kramdown
